name: publish to npm and cdn

on:
  push:
    branches:
      - master
    paths: 
       - 'packages/scu-pecourse-html/package.json'
       - 'packages/scu-pecourse-utils/package.json'
  workflow_dispatch:

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: node --version
      - run: corepack enable
      - run: pnpm i
      - run: pnpm -r build
      - name: publish
        run: |
          pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
          pnpm publish -r --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
